### ISSUE TITLE
Create an Attribute for the cheers for bits-for-bytes--> make code graffitti more useful

### ISSUE THREAD

**Issue by AdmiralSnyder** [csharpfritz/Fritz.Common#1]
hi, wouldn't it be more useful to write the cheering notes as attributes so they can be shift-f12ed and perhaps be displayed in an about dialog?

so instead of code graffitti 
`// someone Cheered 100 on December 10, 2018`
we could have
`[Cheered(100, "someone", 2018, 12, 10)]`
(or some other "useful" date encoding like "20181210"...)

so e.g. an about box could show the Cheerers using reflection...

**Comment by csharpfritz** [comment]
Closed with PR #2
